<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6szyt4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6szyt4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ6szyt4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ6szyt4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ6szyt4\appProdProjectContainer(array(
    'container.build_hash' => 'Z6szyt4',
    'container.build_id' => '08dad558',
    'container.build_time' => 1534497889,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6szyt4');
