<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjg3wsy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjg3wsy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAjg3wsy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAjg3wsy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAjg3wsy\appProdProjectContainer(array(
    'container.build_hash' => 'Ajg3wsy',
    'container.build_id' => 'f0334fd6',
    'container.build_time' => 1534839239,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjg3wsy');
