<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ndqlky\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ndqlky/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7ndqlky.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7ndqlky\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7ndqlky\appDevDebugProjectContainer(array(
    'container.build_hash' => '7ndqlky',
    'container.build_id' => 'f2fa7b7b',
    'container.build_time' => 1536317444,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7ndqlky');
