<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcqmkpt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcqmkpt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUcqmkpt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUcqmkpt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUcqmkpt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ucqmkpt',
    'container.build_id' => '6c3b0d3a',
    'container.build_time' => 1535620427,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcqmkpt');
