<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWioe4lz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWioe4lz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWioe4lz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWioe4lz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWioe4lz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wioe4lz',
    'container.build_id' => '2a6309cd',
    'container.build_time' => 1535538101,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWioe4lz');
